### ISSUE TITLE
Some questions and suggestions

### ISSUE THREAD

**Issue by TheSPD** [deepshaswat/research-air-traffic-system#1]
1. While looking at the plan, I felt it is too vast with mostly learning. 
Feel like the phases could have some learning along with a milestone (an over-simplistic plan could look like)

Phase I    -> Research/Learning about 3D/4D maps
                -> Agreeing on a format to represent 3D data
Phase II   -> Research/Learning about AI/ML 
                -> Design and build a model for the problem
                -> My initial thought was to use _Reinforcement learning_ for this problem - I am not an expert on this topic but we can learn more about it. Some [intro](https://blog.openai.com/openai-five/)
Phase III  -> Research/Learning Client Server - Control room etc,
                -> Build an MVP (Minimum viable product)
Phase III  -> Research/Learning about communication/blockchain
                -> Build a more secure/robust comm module in the app
                -> BTW - My thought on ubiquitousness of _Blockchain_ :stuck_out_tongue_closed_eyes: [here](http://quotegeek.com/quotes-from-movies/jurassic-park/397/)
We can discuss more about this plan.

2. With the ongoing research in self-driven cars, we might not need to place effort in some aspects of the system - like most of the client side [here](https://github.com/deepshaswat/research-air-traffic-system/blob/master/Drone-Traffic.md)

3. Some kind of navigation between the different docs (that help understand a flow) would be awesome.

**Comment by deepshaswat** [comment]
I have updated the basic flow. Please go through and create a new issue if you need some more clarification or have other doubts. Thanks

**Comment by TheSPD** [comment]
Thanks for updating the documents. The flow's pretty clear now. 

On your point 2.1, you're correct in saying that the openAI page is dedicated to games. But what I wanted to highlight is the use of reinforcement learning to achieve this result.

While rest of the ML techniques rely heavily on the use of data, Reinforcement learning eliminates this need of data.

**Comment by deepshaswat** [comment]
Ok..  I have no idea about that. Will look into that. Thanks..
